[package]
name = "clinvoice"
version = "0.1.0"
authors = ["Iron-E <code.iron.e@gmail.com>"]
description = "Invoice from the command line."

categories = ["command-line-utilities", "config", "date-and-time"]
edition = "2018"
keywords = ["invoice", "freelance", "cli", "command", "line", "command-line"]
license = "GPL3"
readme = "./README.md"
repository = "https://www.github.com/Iron-E/clinvoice"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Currency
rusty-money = "0.3"

# Database
serde = {version = "1", features = ["derive"]}
mongodb = {version = "1", default-features = false, features=["sync"]}

# Date/Time
chrono = "0.4"
