# See https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "clinvoice"
version = "0.1.0"
authors = ["Iron-E <code.iron.e@gmail.com>"]
description = "Invoice from the command line."

categories = ["command-line-utilities", "config", "date-and-time"]
edition = "2018"
keywords = ["invoice", "freelance", "cli", "command", "line", "command-line"]
license = "GPL3"
readme = "./README.md"
repository = "https://www.github.com/Iron-E/clinvoice"

[dependencies]
# Arguments
structopt = "0.3"

# CLInvoice
clinvoice_adapter = {path='crates/adapters/clinvoice_adapter', version="0.4"}
clinvoice_adapter_bincode = {path='crates/adapters/clinvoice_adapter_bincode', optional=true, version="0.3"}
clinvoice_config = {path='crates/clinvoice_config', version="0.1"}
clinvoice_data = {path='crates/clinvoice_data', version="0.3"}

# Dialogues
dialoguer = "0.7"

# Serialization
serde = "1"
toml = "0.5"

[features]
default = ["bincode"]
bincode = ["clinvoice_adapter_bincode"]

[workspace]
members = [
	"crates/adapters/clinvoice_adapter",
	"crates/adapters/clinvoice_adapter_bincode",
	"crates/clinvoice_config",
	"crates/clinvoice_data",
]
