# See https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "clinvoice"
version = "0.1.0"
authors = ["Iron-E <code.iron.e@gmail.com>"]
description = "Invoice from the command line."

categories = ["command-line-utilities", "config", "date-and-time"]
edition = "2018"
keywords = ["invoice", "freelance", "cli", "command", "line", "command-line"]
license = "GPL3"
readme = "./README.md"
repository = "https://www.github.com/Iron-E/clinvoice"

[[bin]]
bench = false
path = "crates/clinvoice_bin/main.rs"
name = "invoice"

[workspace]
members = ["crates/clinvoice_bin"]
