# clinvoice -s|--store "name_one" new <client> ## NEW

[store]
default = "name_one"
name_one = {adapter="JSON", path="/home/user/Documents/foo"}
name_two = {adapter="POSTGRES", pass="word", user="name"}

[employees]
default_id = 3

[invoices]
default_currency = "USD"

[timesheets]
interval = {minutes=5}
