# See https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "clinvoice_adapter_toml"
version = "0.1.0"
authors = ["Iron-E <code.iron.e@gmail.com>"]
description = "TOML filesystem adapter for CLInvoice."

edition = "2018"
license = "GPL3"
readme = "../../README.md"
repository = "https://www.github.com/Iron-E/clinvoice"

[dependencies]
# CLInvoice
clinvoice_adapter = {path="../clinvoice_adapter", version="0.1"}
clinvoice_data = {path="../../clinvoice_data", version="0.1"}

# Serialization
serde = {version="1", features=["derive"]}
toml = "0.5"
